-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 20:34:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catastro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `catastro` ;

-- -----------------------------------------------------
-- Schema catastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catastro` DEFAULT CHARACTER SET utf8 ;
USE `catastro` ;

-- -----------------------------------------------------
-- Table `catastro`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`ZONA` (
  `NOMBRE` VARCHAR(45) NOT NULL,
  `CONCEJAL` VARCHAR(45) NULL,
  `AREA` INT NOT NULL,
  PRIMARY KEY (`NOMBRE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`VIVIENDA` (
  `CALLE` VARCHAR(40) NOT NULL,
  `NUMERO` INT NOT NULL,
  `CANTIDAD_DE_PERSONAS` INT NULL,
  `NOMBRE_ZONA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CALLE`, `NUMERO`),
  CONSTRAINT `NOMBRE_ZON`
    FOREIGN KEY (`NOMBRE_ZONA`)
    REFERENCES `catastro`.`ZONA` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`BLOQUE` (
  `CALLE` VARCHAR(45) NOT NULL,
  `NUMERO` INT NOT NULL,
  `CANTIDAD_DE_PERSONAS` INT NULL,
  `NOMBRE_ZONA` VARCHAR(45) NULL,
  PRIMARY KEY (`CALLE`, `NUMERO`),
  CONSTRAINT `NOMBRE_ZON`
    FOREIGN KEY (`NOMBRE_ZONA`)
    REFERENCES `catastro`.`ZONA` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`PERSONA` (
  `CABEZA_FAMILIA` VARCHAR(8) NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `NUMERO_TELEFONO` INT NULL,
  `DNI_LID` VARCHAR(8) NOT NULL,
  `CALLE_VIV` VARCHAR(40) NULL,
  `NUMERO_VIV` INT NULL,
  PRIMARY KEY (`DNI_LID`),
  CONSTRAINT `DNI_`
    FOREIGN KEY (`CABEZA_FAMILIA`)
    REFERENCES `catastro`.`PERSONA` (`DNI_LID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CALLE_VIV_`
    FOREIGN KEY (`CALLE_VIV`, `NUMERO_VIV`)
    REFERENCES `catastro`.`VIVIENDA` (`CALLE`,`NUMERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CALLE_VIV`
    FOREIGN KEY(`CALLE_VIV`)
    REFERENCES `catastro`.`BLOQUE` (`CALLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catastro`.`PISO` (
  `CALLE` VARCHAR(45) NOT NULL,
  `NUMERO` INT NOT NULL,
  `PLANTA` INT NOT NULL,
  `LETRA` VARCHAR(1) NOT NULL,
  `SUPERFICIE` INT NOT NULL,
  PRIMARY KEY (`CALLE`, `NUMERO`, `PLANTA`, `LETRA`),
  CONSTRAINT `CALLE_`
    FOREIGN KEY (`CALLE`, `NUMERO`)
    REFERENCES `catastro`.`BLOQUE` (`CALLE`, `NUMERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
