-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 09:38:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `NUUMERO_ZONA` INT NOT NULL,
  `AREA` INT NULL,
  PRIMARY KEY (`NUUMERO_ZONA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BLOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BLOQUE` (
  `CALLE` VARCHAR(45) NOT NULL,
  `NUMERO` INT NOT NULL,
  `CANTIDAD_PERSONAS` INT NULL,
  `NOMBRE_ZONA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CALLE`, `NUMERO`),
  INDEX `NOMBRE_ZONA_idx` (`NOMBRE_ZONA`  ASC),
  CONSTRAINT `NOMBRE_ZONA`
    FOREIGN KEY (`NOMBRE_ZONA`)
    REFERENCES `mydb`.`ZONA` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PISO` (
  `CALLE` VARCHAR(45) NOT NULL,
  `NUMERO` INT NOT NULL,
  `PLANTA` INT NOT NULL,
  `LETRA` VARCHAR(45) NOT NULL,
  `BLOQUE_CALLE` VARCHAR(45) NOT NULL,
  `BLOQUE_NUMERO` INT NOT NULL,
  PRIMARY KEY (`CALLE`, `NUMERO`, `PLANTA`, `LETRA`, `BLOQUE_CALLE`, `BLOQUE_NUMERO`),
  INDEX `fk_PISO_BLOQUE1_idx` (`BLOQUE_CALLE` ASC, `BLOQUE_NUMERO`  ASC),
  CONSTRAINT `fk_PISO_BLOQUE1`
    FOREIGN KEY (`BLOQUE_CALLE` , `BLOQUE_NUMERO`)
    REFERENCES `mydb`.`BLOQUE` (`CALLE` , `NUMERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVIENDA` (
  `CALLE` VARCHAR(45) NOT NULL,
  `NUMERO` INT NOT NULL,
  `CANTIDAD_PERSONAS` INT NULL,
  `NOMBRE_ZONA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CALLE`, `NUMERO`),
  INDEX `NOMBRE_ZONA_idx` (`NOMBRE_ZONA`  ASC),
  CONSTRAINT `NOMBRE_ZONA`
    FOREIGN KEY (`NOMBRE_ZONA`)
    REFERENCES `mydb`.`ZONA` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `DNI` VARCHAR(45) NOT NULL,
  `FECHA_NACIMIENTO` DATE NULL,
  `NOMBRE` INT NULL,
  `TELEFONO` INT NULL,
  `CABEZA_FAMILIA` VARCHAR(45) NOT NULL,
  `FAMILIA` VARCHAR(45) NULL,
  `PISO_CALLE` VARCHAR(45) NOT NULL,
  `PISO_NUMERO` INT NOT NULL,
  `PISO_PLANTA` INT NOT NULL,
  `PISO_LETRA` VARCHAR(45) NOT NULL,
  `PISO_BLOQUE_CALLE` VARCHAR(45) NOT NULL,
  `PISO_BLOQUE_NUMERO` INT NOT NULL,
  `VIVIENDA_CALLE` VARCHAR(45) NOT NULL,
  `VIVIENDA_NUMERO` INT NOT NULL,
  PRIMARY KEY (`DNI`, `PISO_CALLE`, `PISO_NUMERO`, `PISO_PLANTA`, `PISO_LETRA`, `PISO_BLOQUE_CALLE`, `PISO_BLOQUE_NUMERO`, `VIVIENDA_CALLE`, `VIVIENDA_NUMERO`),
  INDEX `fk_PERSONA_PISO1_idx` (`PISO_CALLE` ASC, `PISO_NUMERO` ASC, `PISO_PLANTA` ASC, `PISO_LETRA` ASC, `PISO_BLOQUE_CALLE` ASC, `PISO_BLOQUE_NUMERO`  ASC),
  INDEX `fk_PERSONA_VIVIENDA1_idx` (`VIVIENDA_CALLE` ASC, `VIVIENDA_NUMERO`  ASC),
  CONSTRAINT `fk_PERSONA_PISO1`
    FOREIGN KEY (`PISO_CALLE` , `PISO_NUMERO` , `PISO_PLANTA` , `PISO_LETRA` , `PISO_BLOQUE_CALLE` , `PISO_BLOQUE_NUMERO`)
    REFERENCES `mydb`.`PISO` (`CALLE` , `NUMERO` , `PLANTA` , `LETRA` , `BLOQUE_CALLE` , `BLOQUE_NUMERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSONA_VIVIENDA1`
    FOREIGN KEY (`VIVIENDA_CALLE` , `VIVIENDA_NUMERO`)
    REFERENCES `mydb`.`VIVIENDA` (`CALLE` , `NUMERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CABEZA_FAMILIA`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb`.`PERSONA` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CALLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CALLE` (
  `NOMBRE` VARCHAR(45) NOT NULL,
  `LONGITUD` INT NULL,
  `TIPO` VARCHAR(45) NULL,
  `NOMBRE_ZONA` VARCHAR(45) NOT NULL,
  `ZONA_NOMBRE` VARCHAR(45) NOT NULL,
  `ZONA_NOMBRE1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NOMBRE`, `ZONA_NOMBRE`, `ZONA_NOMBRE1`),
  INDEX `NOMBRE_ZONA_idx` (`NOMBRE_ZONA`  ASC),
  INDEX `fk_CALLE_ZONA1_idx` (`ZONA_NOMBRE`  ASC),
  INDEX `fk_CALLE_ZONA2_idx` (`ZONA_NOMBRE1`  ASC),
  CONSTRAINT `NOMBRE_ZONA`
    FOREIGN KEY (`NOMBRE_ZONA`)
    REFERENCES `mydb`.`ZONA` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALLE_ZONA1`
    FOREIGN KEY (`ZONA_NOMBRE`)
    REFERENCES `mydb`.`ZONA` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALLE_ZONA2`
    FOREIGN KEY (`ZONA_NOMBRE1`)
    REFERENCES `mydb`.`ZONA` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONSTRUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONSTRUCCION` (
  `NUMERO` INT NOT NULL,
  `NOMBRE_CALLE` VARCHAR(45) NOT NULL,
  `ALTURA` INT NULL,
  `AÑO DE CONSTRUCCION` YEAR(4) NULL,
  `CALLE_NOMBRE` VARCHAR(45) NOT NULL,
  INDEX `NOMBRE_CALLE_idx` (`NOMBRE_CALLE`  ASC),
  PRIMARY KEY (`NUMERO`, `CALLE_NOMBRE`),
  INDEX `fk_CONSTRUCCION_CALLE1_idx` (`CALLE_NOMBRE`  ASC),
  CONSTRAINT `NOMBRE_CALLE`
    FOREIGN KEY (`NOMBRE_CALLE`)
    REFERENCES `mydb`.`CALLE` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONSTRUCCION_CALLE1`
    FOREIGN KEY (`CALLE_NOMBRE`)
    REFERENCES `mydb`.`CALLE` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `NUUMERO_ZONA` INT NOT NULL,
  `AREA` INT NULL,
  PRIMARY KEY (`NUUMERO_ZONA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVERO` (
  `UBICACION` VARCHAR(45) NOT NULL,
  `HORA_APERTURA` TIME NULL,
  `HORA_CIERRE` TIME NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `NUMERO_ZONA` INT NOT NULL,
  PRIMARY KEY (`UBICACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
