USE viveros;
DELIMITER //

CREATE TRIGGER trigger_actualizar_stock AFTER INSERT ON PRODUCTO_PEDIDOS FOR EACH ROW
BEGIN
    UPDATE PRODUCTO, PRODUCTO_PEDIDOS SET PRODUCTO.STOCK = PRODUCTO.STOCK - NEW.CANTIDAD
    WHERE PRODUCTO.COD_BARRAS = NEW.ID_PRODUCTO;
END //

DELIMITER ;
