-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 10:07:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema viveros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema viveros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viveros` DEFAULT CHARACTER SET utf8 ;
USE `viveros` ;

-- -----------------------------------------------------
-- Table `viveros`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`VIVERO` (
  `UBICACION` INT NOT NULL,
  `HORA_APERTURA` TIME NULL,
  `HORA_CIERRE` TIME NULL,
  PRIMARY KEY (`UBICACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`ZONA` (
  `NUMERO_ZONA` INT NOT NULL,
  `AREA` INT NULL,
  `VIVERO_UBICACION` INT NOT NULL,
  `ID_PRODUCTO` INT NOT NULL,
  PRIMARY KEY (`NUMERO_ZONA`),
  INDEX `fk_ZONA_VIVERO1_idx` (`VIVERO_UBICACION` ASC)  ,
  INDEX `ID_PRODUCTO_idx` (`ID_PRODUCTO` ASC)  ,
  CONSTRAINT `fk_ZONA_VIVERO1`
    FOREIGN KEY (`VIVERO_UBICACION`)
    REFERENCES `viveros`.`VIVERO` (`UBICACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,   
  CONSTRAINT `ID_PROD`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `viveros`.`PRODUCTO` (`COD_BARRAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `viveros`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`PRODUCTO` (
  `COD_BARRAS` INT NOT NULL,
  `PRECIO` VARCHAR(45) NULL,
  `STOCK` INT NULL,
  PRIMARY KEY (`COD_BARRAS`)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `viveros`.`ZONA_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`ZONA_PRODUCTOS` (
  `ID_ZONA` INT NOT NULL,
  `ID_PRODUCTO` INT NOT NULL,
  PRIMARY KEY (`ID_ZONA`,`ID_PRODUCTO`),
  INDEX `fk_NUM_ZONA_idx` (`ID_ZONA` ASC)  ,
  INDEX `COD_PRODUCTO_idx` (`ID_PRODUCTO` ASC)  ,
  CONSTRAINT `fk_NUM_ZON`
    FOREIGN KEY (`ID_ZONA`)
    REFERENCES `viveros`.`ZONA` (`NUMERO_ZONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,   
  CONSTRAINT `COD_PRODUCT`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `viveros`.`PRODUCTO` (`COD_BARRAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `viveros`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`CLIENTE` (
  `DNI` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `CUENTA FIDELIZACION` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`EMPLEADO` (
  `DNI` INT NOT NULL,
  `COD.SEGURIDAD_SOCIAL` VARCHAR(45) NOT NULL,
  `TIPO_CONTRATO` VARCHAR(45) NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `FECHA_INI` DATE NULL,
  `FECHA_FIN` DATE NULL,
  `NUMERO_ZONA` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `NUMERO_ZONA_idx` (`NUMERO_ZONA` ASC)  ,
  CONSTRAINT `NUMERO_ZON1`
    FOREIGN KEY (`NUMERO_ZONA`)
    REFERENCES `viveros`.`ZONA` (`NUMERO_ZONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viveros`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`PEDIDO` (
  `ID` INT NOT NULL,
  `FECHA` DATE NULL,
  `ID_PRODUCTO` INT NOT NULL,
  `CANTIDAD` INT NULL,
  `CLIENTE_DNI` INT NOT NULL,
  `EMPLEADO_DNI` INT NOT NULL,
  PRIMARY KEY (`ID`, `ID_PRODUCTO`, `CLIENTE_DNI`, `EMPLEADO_DNI`),
  INDEX `ID_PRODUCTO_idx` (`ID_PRODUCTO` ASC)  ,
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_DNI` ASC)  ,
  INDEX `fk_PEDIDO_EMPLEADO1_idx` (`EMPLEADO_DNI` ASC)  ,
  CONSTRAINT `ID_PRODUCT`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `viveros`.`PRODUCTO` (`COD_BARRAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `viveros`.`CLIENTE` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_DNI`)
    REFERENCES `viveros`.`EMPLEADO` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `viveros`.`PRODUCTO_PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viveros`.`PRODUCTO_PEDIDOS` (
  `ID_PRODUCTO` INT NOT NULL,
  `ID_PEDIDO` INT NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`,`ID_PRODUCTO`),
  INDEX `fk_ID_PEDIDO_idx` (`ID_PEDIDO` ASC)  ,
  INDEX `COD_PRODUCTO_idx` (`ID_PRODUCTO` ASC)  ,
  CONSTRAINT `fk_ID_PED`
    FOREIGN KEY (`ID_PEDIDO`)
    REFERENCES `viveros`.`PEDIDO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,   
  CONSTRAINT `COD_PRODUCT1`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `viveros`.`PRODUCTO` (`COD_BARRAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    )
ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
